### ISSUE TITLE
qeRFranger

### ISSUE THREAD

**Issue by nks1974** [matloff/qeML#1]
in function code for qeRFranger, rfrout is misspelled as rfout (last line here)

>  rfrout$classNames <- xyc$classNames                                                                                                   
>     rfrout$classif <- classif                                                                                                                                               
>     rfrout$trainRow1 <- getRow1(data, yName)                                                                                                                                    
>     rfout$yYesName <- yYesName

**Comment by nks1974** [comment]
New error this morning (note, there is still the aforementioned spelling error that will also cause an error)

ranger_0.13.1                                                                                                                                                           qeML_1.1                                                                                                                                                               
regtools_1.7.0  

>   t.train <- cbind( target=(as.factor(iris$Species=='virginica')), iris)                                                                                                                                                                                                      
>   m.rfr <- qeRFranger(data=t.train, yName='target')                                                                                                                                                                                                                           
holdout set has  15 rows                                                                                                                                                                                                                                                        
Error in rangerCpp(treetype, x, y.mat, independent.variable.names, mtry,  :                                                                                                                                                                                                     
  object '_ranger_rangerCpp' not found

**Comment by matloff** [comment]
Yes, will fix, thanks very much!

**Comment by matloff** [comment]
Fixed, sorry for the long delay.
