### ISSUE TITLE
Hyperparameter Tuning: Looking for Examples

### ISSUE THREAD

**Issue by larry77** [matloff/qeML#14]
I would like to give qeml a try since it does look simpler than the competition ;-) .
Mine is a question rather than a proper issue (but there is no discussion session for this repo).
I may be unable to find this information, but is there any example of hyperparameter tuning anywhere?
I am after the "usual" grid search for one or more hyperparameters combined with cross validation.
Thanks a lot.

**Comment by matloff** [comment]
Yes, the function qeFT does this, and there is an example in the online help; type ?qeFT. There is more extensive material in my book, The Art of Machine Learning, which uses the qeML package; Chapter 7 is devoted to this topic. However, again, the online help for qeFT should be all you need.

**Comment by larry77** [comment]
Thanks. I am closing this issue now and will have a look at the book and the online help. Will reopen it if needed.
