### ISSUE TITLE
qeKNN, not seeing holdout count message

### ISSUE THREAD

**Issue by dwormuth** [matloff/qeML#15]
Installed version 1.2 10/2/24. Code seems to work (using the Art of Machine Language book from No Starch Press). 

When I run the code, I don't see the "holdout set has XX cases" message. Not sure if this is a bug or a feature. Also, the resulting variable (for day1 and MLB) has 20 rows.

**Comment by matloff** [comment]
Yes, the message was removed in later versions of qeML.

As to the issue of 20 rows, I'm not sure what you mean. The number of rows is still 101:

> length(z$holdIdxs)
[1] 101

**Comment by dwormuth** [comment]
Thanks for the clarification on the holdout message.

As to the 20, that was my error reading RDesktop variable lists.
