### ISSUE TITLE
qeROC call

### ISSUE THREAD

**Issue by carbonmetrics** [matloff/qeML#7]
page 47:

`w <- qeROC(tc,knnout,'Churn','Yes')`

but this does not work, because the function has 3 arguments instead of 4:
`function (dataIn, qeOut, yLevelName) `

the example works with:
`w = qeROC(dataIn = tc, qeOut = knnout, yLevelName = "Yes")`

but that inverts the curve.
works as foreseen via
`w = qeROC(dataIn = tc, qeOut = knnout, yLevelName = "No")`

btw - the no-show data set page 42 footnote 3 has the problem that the original Y name = "No-show", which is invalid in R.

**Comment by matloff** [comment]
Thanks so much for uncovering this error in the book. The 'yName' argument should not be in the calls. I've now added an entry to the [Errata file](https://github.com/matloff/ArtOfML/blob/main/Errata/Errata.md).
