### ISSUE TITLE
vignette() does not find md files

### ISSUE THREAD

**Issue by nks1974** [matloff/qeML#8]
vignette( 'Quick_Start' )

results in

'vignette 'Quick_Start' not found.

Files are located in default libPaths package folder qeML/mdFiles and open correctly in a okular.

**Comment by matloff** [comment]
How did you install qeML?

**Comment by nks1974** [comment]
gibhub bad, cran good, as of today.

Installing from github it produces the error after library(). Vignette does not find the md files.

From cran it works well. Vignette finds and opens the md files.

The error was reproduced several times with remove.packages(), re-installation of qeML from github and cran, and doing R restart.

In one case, it might have worked from github if R itself was updated after installing from qeML github.

**Comment by matloff** [comment]
If you install from GitHub, I recommend

remotes::install_github('https://github.com/matloff/qeML',dependencies=TRUE,build_vignettes=TRUE)

**Comment by nks1974** [comment]
Yes, that command makes vignette work with the github installation.
