### ISSUE TITLE
fortran 2018?

### ISSUE THREAD

**Issue by jimrothstein** [matloff/qeML#9]
Errors installing `qeML` or several dependencies, such as `minqa` ??
Thx:

R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 21.2

``` r
install.packages("minqa")
#> Installing package into '/home/jim/R/x86_64-pc-linux-gnu-library/4.3'
#> (as 'lib' is unspecified)
#> Warning in install.packages("minqa"): installation of package 'minqa' had
#> non-zero exit status
```

``` sh
trying URL 'https://cloud.r-project.org/src/contrib/minqa_1.2.6.tar.gz'
Content type 'application/x-gzip' length 54493 bytes (53 KB)
==================================================
downloaded 53 KB


  -----------------------------------------  

* installing *source* package ‘minqa’ ...
** package ‘minqa’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using Fortran compiler: ‘GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
gfortran  -fpic  -g -O2  -c altmov.f -o altmov.o
altmov.f:42:72:

   42 |    10 HCOL(K)=ZERO
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 10 at (1)
altmov.f:45:72:

   45 |       DO 20 K=1,NPT
      |                                                                        1
Warning: Fortran 2018 deleted feature: Shared DO termination label 20 at (1)
altmov.f:46:72:

   46 |    20 HCOL(K)=HCOL(K)+TEMP*ZMAT(K,J)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 20 at (1)
altmov.f:53:72:

<SNIP>

.
.
<SNIP>

Warning: Fortran 2018 deleted feature: Shared DO termination label 60 at (1)
g++ -std=gnu++17 -shared -L/opt/R/4.3.1/lib/R/lib -L/usr/local/lib -o minqa.so altmov.o bigden.o biglag.o bobyqa.o bobyqb.o lagmax.o minqa.o newuoa.o newuob.o prelim.o rescue.o trsapp.o trsbox.o trstep.o uobyqa.o uobyqb.o update.o updatebobyqa.o ----------------------------------------- -lgfortran -lm -lquadmath -L/opt/R/4.3.1/lib/R/lib -lR
g++: error: unrecognized command-line option ‘-----------------------------------------’
make: *** [/opt/R/4.3.1/lib/R/share/make/shlib.mk:10: minqa.so] Error 1
ERROR: compilation failed for package ‘minqa’
* removing ‘/home/jim/R/x86_64-pc-linux-gnu-library/4.3/minqa’

The downloaded source packages are in
	'/tmp/Rtmp3riSHb/downloaded_packages'
```

**Comment by matloff** [comment]
That's pretty weird. Try downloading the source from

https://cran.r-project.org/src/contrib/minqa_1.2.6.tar.gz

and then running (from the shell)

R CMD INSTALL -l /home/jim/R/x86_64-pc-linux-gnu-library/4.3
 minqa_1.2.6.tar.gz


Norm

**Comment by jimrothstein** [comment]
Looks like same:   

**R CMD INSTALL -l /home/jim/R/x86_64-pc-linux-gnu-library/4.3
 minqa_1.2.6.tar.gz  2>  result.txt**


* installing *source* package ‘minqa’ ...
** package ‘minqa’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using Fortran compiler: ‘GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
altmov.f:42:72:

   42 |    10 HCOL(K)=ZERO
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 10 at (1)
altmov.f:45:72:

   45 |       DO 20 K=1,NPT
      |                                                                        1
Warning: Fortran 2018 deleted feature: Shared DO termination label 20 at (1)
altmov.f:46:72:

   46 |    20 HCOL(K)=HCOL(K)+TEMP*ZMAT(K,J)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 20 at (1)
altmov.f:53:72:

   53 |    30 GLAG(I)=BMAT(KNEW,I)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 30 at (1)
altmov.f:57:72:

   57 |    40 TEMP=TEMP+XPT(K,J)*XOPT(J)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 40 at (1)
altmov.f:59:72:

   59 |       DO 50 I=1,N
      |                                                                        1
Warning: Fortran 2018 deleted feature: Shared DO termination label 50 at (1)
altmov.f:60:72:

   60 |    50 GLAG(I)=GLAG(I)+TEMP*XPT(K,I)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 50 at (1)
altmov.f:76:72:

   76 |    60 DISTSQ=DISTSQ+TEMP*TEMP
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 60 at (1)
altmov.f:173:72:

<SNIP>
<SNIP>.
.
Warning: Fortran 2018 deleted feature: Shared DO termination label 60 at (1)
g++: error: unrecognized command-line option ‘-----------------------------------------’
make: *** [/opt/R/4.3.1/lib/R/share/make/shlib.mk:10: minqa.so] Error 1
ERROR: compilation failed for package ‘minqa’
* removing ‘/home/jim/R/x86_64-pc-linux-gnu-library/4.3/minqa’

**Comment by matloff** [comment]
I urge you to contact Kate Mullen, maintainer of the minqa package. He should be able to help solve your problem.
